# Generated by Django 5.2.4 on 2025-08-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisador', '0003_extrato_transacao_extrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='origem_descricao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
