# Generated by Django 5.2.4 on 2025-08-07 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analisador', '0004_transacao_origem_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transacao',
            name='origem_descricao',
        ),
    ]
