# Generated by Django 5.2.4 on 2025-08-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisador', '0005_remove_transacao_origem_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='origem_descricao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
