# Generated by Django 5.2.4 on 2025-08-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisador', '0006_transacao_origem_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='categorizacao_manual',
            field=models.BooleanField(default=False),
        ),
    ]
